# Generated by Django 5.0.1 on 2024-01-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('vendor', 'Vendor'), ('customer', 'Customer')], max_length=10, null=True)),
            ],
        ),
    ]
