# Generated by Django 5.0.1 on 2024-01-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_role_switch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
